const constants = {
  RECTANGLES_TO_GENERATE: 5,
  RECTANGLE_MIN_WIDTH: 70,
  RECTANGLE_MIN_HEIGHT: 45,
  RECTANGLE_MAX_WIDTH: 400,
  RECTANGLE_MAX_HEIGHT: 90,
  CONTAINER_PADDING: 100,
  RED_COLOR: '#da3d4b',
  OFFSET_PAGE: 100,
  OFFSET_CONNECTION: 25,
  OFFSET_BETWEEN_RECTANGLES: 70,
};

export {
  constants,
};
